# Generated by Django 4.0.1 on 2022-01-26 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_rename_introductionlevel_anime_character_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
