# Generated by Django 4.0.1 on 2022-01-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_alter_anime_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='creator',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
