# Generated by Django 4.0.1 on 2022-01-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0005_anime_image_alter_creator_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='image',
            field=models.URLField(default='www.google.com', max_length=1000),
        ),
    ]
