# Generated by Django 4.0.1 on 2022-01-29 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0006_alter_anime_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='character',
            new_name='favortieCharacter',
        ),
        migrations.AddField(
            model_name='creator',
            name='birthyear',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='creator',
            name='country',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='creator',
            name='image',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='image',
            field=models.CharField(default='www.google.com', max_length=1000),
        ),
    ]
