# Generated by Django 4.0.1 on 2022-01-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0007_rename_character_anime_favortiecharacter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='birthyear',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='creator',
            name='country',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='creator',
            name='image',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='creator',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
