# Generated by Django 4.0.1 on 2022-01-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0008_alter_creator_birthyear_alter_creator_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='birthyear',
            field=models.IntegerField(),
        ),
    ]
