# Generated by Django 4.0.1 on 2022-01-29 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0009_alter_creator_birthyear'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creator',
            old_name='birthyear',
            new_name='birth_year',
        ),
    ]
