# Generated by Django 4.0.1 on 2022-01-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0010_rename_birthyear_creator_birth_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
