# Generated by Django 4.0.1 on 2022-01-29 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0011_alter_creator_birth_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='birth_year',
        ),
    ]
